// Reporting / export: plain-text and CSV report builders that preserve
// source attribution. Served as downloads by /api/export/*.
import type { Db } from "../db";
import { parseJson } from "../validate";

export async function siteReport(db: Db, siteId: string, viewerId: string): Promise<string> {
  const site = await db.site.findUniqueOrThrow({
    where: { id: siteId },
    include: { directors: true, observations: true, visits: true, vendorSites: { include: { vendor: true } }, contracts: { include: { contract: true } }, projects: true },
  });
  const lines = [
    `SITE REPORT — ${site.name} (${site.code})`,
    `Location: ${site.location ?? "—"}`,
    `Generated by Crothall Executive OS`,
    "",
    `DIRECTORS (${site.directors.length})`,
    ...site.directors.map((d) => `  - ${d.name}${d.title ? `, ${d.title}` : ""} [/directors/${d.id}]`),
    "",
    `PROJECTS (${site.projects.length})`,
    ...site.projects.map((p) => `  - ${p.name} — ${p.status}`),
    "",
    `VENDORS (${site.vendorSites.length})`,
    ...site.vendorSites.map((v) => `  - ${v.vendor.name} [/vendors/${v.vendorId}]`),
    "",
    `CONTRACTS (${site.contracts.length})`,
    ...site.contracts.map((c) => `  - ${c.contract.title}${c.contract.endDate ? ` (ends ${c.contract.endDate.toDateString()})` : ""} [/contracts/${c.contractId}]`),
    "",
  ];
  for (const category of ["POSITIVE", "IMPROVEMENT", "TRAINING", "CRITICAL", "BACKBURNER"] as const) {
    const obs = site.observations.filter((o) => o.category === category);
    if (obs.length) {
      lines.push(`${category} (${obs.length})`);
      lines.push(...obs.map((o) => `  - ${o.content} (${o.createdAt.toDateString()})`));
      lines.push("");
    }
  }
  lines.push(`SITE VISITS (${site.visits.length})`);
  lines.push(...site.visits.map((v) => `  - ${v.startedAt.toDateString()} — ${v.status}${v.summary ? `: ${v.summary}` : ""}`));
  return lines.join("\n");
}

export async function directorReport(db: Db, directorId: string, viewerId: string): Promise<string> {
  const director = await db.director.findUniqueOrThrow({
    where: { id: directorId },
    include: { site: true, infractions: true, fileEntries: { where: { OR: [{ visibility: "SHARED" }, { createdById: viewerId }] } } },
  });
  const lines = [
    `DIRECTOR OPERATIONAL HISTORY — ${director.name}`,
    `Site: ${director.site?.name ?? "—"}`,
    `Generated by Crothall Executive OS`,
    "",
    `INFRACTIONS (${director.infractions.length})`,
    ...director.infractions.map((i) => `  - ${i.date.toDateString()} [${i.severity}] ${i.category}: ${i.description} — status ${i.status} [/directors/${directorId}]`),
    "",
    `FILE ENTRIES (${director.fileEntries.length}, authorized only)`,
    ...director.fileEntries.map((e) => `  - ${e.createdAt.toDateString()} [${e.classification}] ${e.content.slice(0, 200)}`),
  ];
  return lines.join("\n");
}

export async function vendorReport(db: Db, vendorId: string): Promise<string> {
  const vendor = await db.vendor.findUniqueOrThrow({
    where: { id: vendorId },
    include: { performance: true, contracts: true, sites: { include: { site: true } } },
  });
  return [
    `VENDOR REPORT — ${vendor.name}`,
    `Generated by Crothall Executive OS`,
    "",
    `SITES SERVED: ${vendor.sites.map((s) => s.site.name).join(", ") || "—"}`,
    `CONTRACTS: ${vendor.contracts.map((c) => c.title).join(", ") || "—"}`,
    "",
    `PERFORMANCE HISTORY (${vendor.performance.length})`,
    ...vendor.performance.map((p) => `  - ${p.createdAt.toDateString()} [${p.type}] ${p.content} [/vendors/${vendorId}]`),
  ].join("\n");
}

export async function meetingReport(db: Db, meetingId: string): Promise<string> {
  const m = await db.meeting.findUniqueOrThrow({ where: { id: meetingId } });
  const decisions = parseJson<string[]>(m.decisionsJson, []);
  const actions = parseJson<{ title: string; owner?: string; due?: string }[]>(m.actionsJson, []);
  const unresolved = parseJson<string[]>(m.unresolvedJson, []);
  return [
    `MEETING REPORT — ${m.title}`,
    m.heldAt ? `Held: ${m.heldAt.toDateString()}` : "",
    `Analysis mode: ${m.analysisMode ?? "pending"}`,
    "",
    `SUMMARY`,
    m.summary ?? "(not analyzed)",
    "",
    `DECISIONS (${decisions.length})`,
    ...decisions.map((d) => `  - ${d}`),
    "",
    `ACTIONS (${actions.length})`,
    ...actions.map((a) => `  - ${a.title}${a.owner ? ` (owner: ${a.owner})` : ""}${a.due ? ` due ${a.due}` : ""}`),
    "",
    `UNRESOLVED (${unresolved.length})`,
    ...unresolved.map((u) => `  - ${u}`),
    "",
    `Source: /meetings/${meetingId}`,
  ].filter((l) => l !== "").join("\n");
}

export async function activityReport(db: Db, userId: string, from: Date, to: Date): Promise<string> {
  const events = await db.activityEvent.findMany({
    where: { userId, occurredAt: { gte: from, lte: to } },
    orderBy: { occurredAt: "asc" },
  });
  return [
    `EXECUTIVE ACTIVITY REPORT`,
    `${from.toDateString()} — ${to.toDateString()}`,
    `Generated by Crothall Executive OS`,
    "",
    ...events.map((e) => `${e.occurredAt.toISOString().slice(0, 16).replace("T", " ")}  [${e.type}] ${e.summary}`),
  ].join("\n");
}
